[2024-04-21T15:02:21.362+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: api_dag.get_posts manual__2024-04-21T15:02:19.571583+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
